"""Ask the RDS encoder what it supports, and what it does to our text.

Run with no arguments, it prints the encoder's full HELP command list and the current
RT+ state, and changes nothing. That is how we established that this unit has no ASCII
command for RT+ tags — the entire RT+ surface is RT_PLUS_AUTO and RT_PLUS — so the tags
have to be generated by the encoder from the RadioText the service sends.

With --write it also sends a RadioText containing the awkward characters and reads the
stored value back, showing what the encoder keeps, strips or substitutes before anything
reaches a receiver.

    uv run probe_rtplus.py              # read-only
    uv run probe_rtplus.py --write      # also does the character round-trip
    uv run probe_rtplus.py --port=5423  # try the old router mapping instead of 23

STOP THE SERVICE FIRST. The encoder allows a limited number of telnet sessions and the
LaunchAgent holds one permanently — a second connection is then accepted by TCP but
never answered, which looks exactly like a dead port:

    launchctl unload ~/Library/LaunchAgents/org.wxdu.rds-now-playing.plist
    ... run the probe ...
    launchctl load ~/Library/LaunchAgents/org.wxdu.rds-now-playing.plist

RadioText holds on the last song while the service is stopped; it does not go silent.
--write changes the on-air RadioText for a few seconds, so pick a quiet moment. The
original is read first and put back at the end.
"""

import socket
import sys
import time
from pathlib import Path

_env = dict(
    line.strip().split("=", 1)
    for line in Path(".env").read_text().splitlines()
    if line.strip() and not line.startswith("#")
)
HOST = _env["RDS_IP"]
LOGIN = _env["RDS_LOGIN"]
PASSWORD = _env["RDS_PASSWORD"]
CONFIG_PORT = int(_env.get("RDS_PORT", "23"))   # accepts every command, prompts for login
for _arg in sys.argv[1:]:                       # --port=5423 to try the old mapping
    if _arg.startswith("--port="):
        CONFIG_PORT = int(_arg.split("=", 1)[1])

# Sending a command name with no "=" reads its current value back; an unsupported name
# answers "!". HELP prints the whole command list, which is the authoritative reference
# for this firmware — more complete than the PDF manual.
QUERIES = [
    "RDS.PI",           # station identity, confirms we're talking to the right unit
    "RDS.RT",           # current RadioText
    "RDS.GS",           # group sequence — an RT+ group must appear here to be transmitted
    "SEQ3A",            # 3A sequence, which announces the RT+ ODA to receivers
    "RT_PLUS",          # which group carries RT+ (0 = off)
    "RT_PLUS_AUTO",     # 1 = encoder derives the tags from the RadioText itself
    "ODA.1B.AID",
    "ODA.13B.AID",
    "HELP",
]

# Every character that the RDS G0 code table places somewhere other than ASCII does,
# plus the two truncation marks we care about.
PROBE_TEXT = "WXDU probe ~ > * . $ ^ ` end"


def read_for(sock, seconds, until=None):
    """Read for up to `seconds`, stopping early on `until`. Returns (text, closed)."""
    deadline = time.monotonic() + seconds
    chunks = []
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return b"".join(chunks).decode("utf-8", "replace"), False
        sock.settimeout(remaining)
        try:
            data = sock.recv(4096)
        except socket.timeout:
            return b"".join(chunks).decode("utf-8", "replace"), False
        except OSError:
            # Reset by the peer, or by something in between — same as a close here
            return b"".join(chunks).decode("utf-8", "replace"), True
        if not data:
            return b"".join(chunks).decode("utf-8", "replace"), True
        chunks.append(data)
        text = b"".join(chunks).decode("utf-8", "replace")
        if until and until in text.upper():
            return text, False


def send(sock, line, wait=1.0):
    sock.sendall((line + "\r\n").encode("utf-8"))
    return read_for(sock, wait)[0]


def show(label, response):
    body = response.strip() or "(no response)"
    print(f"  {label:<34} -> {body!r}")


def connect(port, login=True, patience=15.0):
    """Connect and log in, reporting exactly what the encoder does and doesn't say."""
    started = time.monotonic()
    sock = socket.create_connection((HOST, port), timeout=15)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
    print(f"  TCP connect to {HOST}:{port} succeeded in {time.monotonic() - started:.1f}s")

    banner, closed = read_for(sock, patience, until="LOGIN")
    print(f"  banner after {time.monotonic() - started:.1f}s -> {banner.strip()!r}")
    if closed:
        print("  !! the encoder closed the connection immediately.")
        return sock, banner

    if not banner.strip():
        # Some units stay silent until they see a newline. Nudge it before giving up.
        print("  nothing yet — sending a bare newline to prompt it...")
        try:
            sock.sendall(b"\r\n")
            more, closed = read_for(sock, patience, until="LOGIN")
        except OSError as e:
            print(f"  connection dropped when nudged: {e}")
            more = ""
        print(f"  after nudge -> {more.strip()!r}")
        banner += more

    if not banner.strip():
        print()
        print("  !! Connected, but the encoder never sent anything. The usual cause is")
        print("     that it allows only a limited number of telnet sessions and the")
        print("     LaunchAgent already holds one. Stop the service and run this again:")
        print("       launchctl unload ~/Library/LaunchAgents/org.wxdu.rds-now-playing.plist")
        print("     (RadioText freezes on the last song until you load it back; it does")
        print("      not go silent.) If it is still quiet with the service stopped, then")
        print("     something between here and the encoder is accepting the connection")
        print("     without passing it through — check the router's port-23 forward.")
        return sock, banner

    if login:
        # Send credentials whenever a prompt showed up at all, rather than insisting
        # on seeing it inside one short window.
        send(sock, LOGIN, wait=3.0)
        response = send(sock, PASSWORD, wait=3.0)
        print(f"  after login -> {response.strip()!r}")
        if "LOGGED" not in response.upper():
            print("  !! no LOGGED confirmation — check RDS_LOGIN / RDS_PASSWORD in .env")
        banner += response

    return sock, banner


def main():
    write_mode = "--write" in sys.argv
    print(f"Connecting to {HOST}:{CONFIG_PORT} (configuration port)\n")

    sock, banner = connect(CONFIG_PORT)
    if not banner.strip():
        print("\nStopping here — no point sending commands into silence.")
        sock.close()
        return

    print("\nRead-only queries:")
    for query in QUERIES:
        show(query, send(sock, query, wait=2.0))

    if not write_mode:
        print("\nRead-only pass done. Re-run with --write for the character round-trip")
        print("(changes the on-air RadioText for a few seconds, then puts it back).")
        sock.close()
        return

    # The encoder answers a read with the bare value, not "RDS.RT=<value>", so this is
    # the text itself and can go straight back in an RT_TEXT= command afterwards.
    original = send(sock, "RDS.RT", wait=2.0).strip()
    print(f"\nCurrent RadioText, will be restored: {original!r}")

    print(f"\nCharacter round-trip — sending {PROBE_TEXT!r}:")
    send(sock, "RT_TEXT=" + PROBE_TEXT)
    time.sleep(1.0)
    show("RDS.RT readback", send(sock, "RDS.RT", wait=2.0))
    print("  ^ anything dropped or altered here never reaches a receiver at all.")
    print("    A character surviving does NOT prove a receiver will draw it correctly —")
    print("    the RDS G0 code table decides that. This only rules the encoder in or out.")

    if original:
        send(sock, "RT_TEXT=" + original)
        print(f"\nRestored: {original!r}")
    else:
        print("\nNothing to restore — the service will set the text on its next poll.")

    sock.close()


if __name__ == "__main__":
    try:
        main()
    except OSError as e:
        print(f"\nCould not talk to the encoder at {HOST}:{CONFIG_PORT} — {e}")
        print("If this is a timeout, the port is filtered rather than closed; check the")
        print("router's forward. Try --port=5423 to see whether the old mapping answers.")
